FROM node:18-bookworm-slim AS base

WORKDIR /app

COPY ./package*.json /app
RUN npm ci --omit=dev

FROM base AS builder

WORKDIR /app

COPY . /app
RUN npm ci && npm run build && npm run package

FROM node:18-bookworm-slim AS final

WORKDIR /app

COPY --from=base /app/. /app/.
COPY --from=builder /app/dist/. /app/dist/.

EXPOSE 3000/tcp

ENTRYPOINT ["node", "/app/dist/index.js"]
