{{- if .Values.envVarsSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-stream.fullname" . }}-secrets
  labels:
    {{- include "notification-stream.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $name, $secret := .Values.envVarsSecrets }}
  {{ $name }}: {{ $secret | b64enc }}
{{- end }}
{{- end }}
